name: devin
favicon: null
layout_spectrum: 0.21724858647212386
typography_spectrum: 0.644118869677186
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.7730275860521942
  lightness: 0.6747875888831913
  saturation: 0.36394563713110983
  rhythmicContrast: 0.4158613961189985
purpose: []
