name: devin
favicon: null
layout_spectrum: 0.72123
typography_spectrum: 0.30743
title: "there's gold in them there cushions"
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#78a0d3'
    - '#211007'
    - '#dc2a1b'
    - '#0d307e'
    - '#405a8a'
  brandStrength: 0.75
  lightness: 0.8125
  saturation: 0.3125
  rhythmicContrast: 0.75
purpose: []
