name: devin
favicon: null
layout_spectrum: 1
typography_spectrum: 0.28633
title: "there's gold in them there cushions"
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#d1eafe'
    - '#b8aea4'
    - '#fefefd'
    - '#8c7a70'
    - '#3b2720'
  brandStrength: 0.875
  lightness: 0.625
  saturation: 0.1875
  rhythmicContrast: 0.5
purpose: []
